sudo: required
services:
  - docker
script:
  - docker build -t starter_image_ci .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag starter_image_ci $DOCKER_USER/starter_image_ci
  - docker push $DOCKER_USER/starter_image_ci